### ISSUE TITLE
Issue Installing MRAID

### ISSUE THREAD

**Issue by karinkumar** [yuanzhongshang/MRAID#1]
Hello I am trying to install MRAID and getting the following error message: 

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [MRAID.so] Error 1
ERROR: compilation failed for package ‘MRAID’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/MRAID’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/c2/5ksg_m2x2s12wrg58xkrp4fw0000gn/T//RtmpQoKMoF/file5b9164c83e9b/MRAID_1.0.tar.gz’ had non-zero exit status

I haven't had any other issues installing R packages in R recently so I'm wondering if this has something to do with MRAID?

**Comment by yuanzhongshang** [comment]
Hello,
Thanks for your interest with the MRAID method. From your error message, we speculate you are using a mac system. Under mac system, you need to install gfortran in -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 according to the error message. You can perform the following steps on the mac terminal to solve the issue.
Step1: install brew
   Step2: install gcc
        brew install gcc
   Step3: create a new path
        sudo mkdir -p /usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0
   Step4: copy gcc from step2 to the path in step3
        sudo cp  /usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/*  /usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0
        (where /usr/local/Cellar/gcc/9.2.0_3/lib/gcc/9/* is the path of gcc including gfortran)
   Step5: install MRAID
        # install.packages("devtools")
library(devtools)
install_github("yuanzhongshang/MRAID")

Please do not hesitate to contact us if you have any questions.

Bests,
Zhongshang
