### ISSUE TITLE
Issue with Gibbs sampler when standard errors are small

### ISSUE THREAD

**Issue by jean997** [yuanzhongshang/MRAID#2]
Hi Zhongshang,
Thank you for making this nice method!

We have been experimenting with it and have mostly gotten very good results but ran into some issues where it seems like the Gibbs sampler may be failing to explore the whole likelihood leading to occasionally very "off" estimates. We found that artificially increasing the noise of the estimates solves the problem so it could be related to the sampling strategy or step size. 

I am attaching an example data set where we see the issue. In this data, the true causal effect is 0.1. The sample size for trait 1 is 10k and the sample size for trait 2 is 500k. If we run MRAID on the original data, it usually generates a causal estimate near -0.05

```
library(dplyr)
library(MRAID)
library(purrr)
dat <- readRDS("mraid_debug_data.RDS")
set.seed(1)
fit_orig <-  replicate(n = 10, expr = { with(dat,
                                             MRAID(Zscore_1 = SNP_data$bx/SNP_data$bxse,
                                                   Zscore_2 = SNP_data$by/SNP_data$byse,
                                                   Sigma1sin = LD_matrix,
                                                   Sigma2sin = LD_matrix,
                                                   samplen1 = 10000, samplen2 = 500000,
                                                   burninproportion = 0.2, Gibbsnumber = 1000))}, simplify = FALSE)
map(fit_orig, "causal_effect") %>% unlist()
# [1] -0.04894335 -0.04813901 -0.05256924 -0.04656615 -0.05139219 -0.05226496 -0.05669891 -0.04600676 -0.04565323 -0.05410061
``` 
In this example, the sampler is always giving a similar result, though we have also seen examples where we get a range of results over different runs of MRAID. 

However, when we artificially increase the standard error for trait 2 estimates and decrease the trait 2 sample size we get much better solutions and MRAID consistently gives the same/similar results over multiple runs:

```
fit_more_noise <-  replicate(n = 10, expr = { with(dat,
                                             MRAID(Zscore_1 = SNP_data$bx/SNP_data$bxse,
                                                   Zscore_2 = SNP_data$by/(sqrt(10)*SNP_data$byse),
                                                   Sigma1sin = LD_matrix,
                                                   Sigma2sin = LD_matrix,
                                                   samplen1 = 10000, samplen2 = 50000,
                                                   burninproportion = 0.2, Gibbsnumber = 1000))}, simplify = FALSE)
map(fit_more_noise, "causal_effect") %>% unlist()
# [1] 0.09584193 0.09732339 0.09578834 0.09525779 0.09496835 0.09560519 0.09525171 0.09473296 0.09605512 0.09543104
```

We were hoping to find a solution to this issue. Perhaps you could add user facing options for tuning the Gibbs sampler. Also -- would it be possible to return the likelihood at the the returned solution? That would help in diagnosing which mode was better if we see multiple solutions over several runs.

Thanks!
Jean
[mraid_debug_data.RDS.tar.gz](https://github.com/yuanzhongshang/MRAID/files/10071853/mraid_debug_data.RDS.tar.gz)

**Comment by yuanzhongshang** [comment]
Hi Jean,
Thanks for your valuable suggestions, I will read carefully your comments and oprimize the package as soon as poosible.
Bests,
Zhongshang
