### ISSUE TITLE
Error in lm.wfit(x, y, w, offset = offset, singular.ok = singular.ok,  :    0 (non-NA) cases

### ISSUE THREAD

**Issue by llalluan** [yuanzhongshang/MRAID#3]
Hi,
I try to perform MR analysis with MRAID on data with 78 IVs, and I get the message `Error in lm.wfit(x, y, w, offset = offset, singular.ok = singular.ok,  :    0 (non-NA) cases`. I don‘t know why?  it seems not due to the number of IVs. 
Thanks for any help!

**Comment by SMUJK** [comment]
Hi,
I also met the problem and then I checked the original code of the function. I found that the IVs used for input might be way correlated, so all the IVs are filtered out with the LD threshold of 0.25. You should try other IVs that are relatively less correlated. That is my solution for the problem.

**Comment by llalluan** [comment]
> 

Thanks a lot! I'll try it.

**Comment by llalluan** [comment]
> Hi, I also met the problem and then I checked the original code of the function. I found that the IVs used for input might be way correlated, so all the IVs are filtered out with the LD threshold of 0.25. You should try other IVs that are relatively less correlated. That is my solution for the problem.



> Hi, I also met the problem and then I checked the original code of the function. I found that the IVs used for input might be way correlated, so all the IVs are filtered out with the LD threshold of 0.25. You should try other IVs that are relatively less correlated. That is my solution for the problem.

Thanks a lot! I'll try it
