### ISSUE TITLE
do i need to evaluate whether correlated or uncorrelated pleiotropy effect is significant

### ISSUE THREAD

**Issue by arkyl** [yuanzhongshang/MRAID#5]
Hi,
Thanks a lot for the MRAID software and congratulations on your publication.
I noticed that there are some outputs on pleiotropy effects: 1) on correlated pleiotropy effect, namely "correlated_pleiotropy_effect", and 2) on uncorrelated pleiotropy effect, namely "sigmaeta", which is "The variance estimate for the uncorrelated pleiotropy effect".
Do I need to evaluate the pleiotropy effect based on these outputs? or MRAID already accounts for both pleiotropy effects, so the results "causal_effect" and "causal_pvalue" are already the results after accounted for pleiotropy. 
Thanks a lot for your help.

Best,
Yue

**Comment by yuanzhongshang** [comment]
Hi Yue,

Thanks for your interest with the MRAID method. 

The output "causal_effect" and "causal_pvalue" from MRAID are already the results after accounting for pleiotropy.Indeed, accounting for different types of pleiotropy is the main advantage of MRAID.

Please do not hesitate to contact me if you have further questions.




Bests,

Zhongshang








-----原始邮件-----
发件人:ylark ***@***.***>
发送时间:2024-09-18 09:51:20 (星期三)
收件人: yuanzhongshang/MRAID ***@***.***>
抄送: Subscribed ***@***.***>
主题: [yuanzhongshang/MRAID] do i need to evaluate whether correlated or uncorrelated pleiotropy effect is significant (Issue #5)






Hi,
Thanks a lot for the MRAID software and congratulations on your publication.
I noticed that there are some outputs on pleiotropy effects: 1) on correlated pleiotropy effect, namely "correlated_pleiotropy_effect", and 2) on uncorrelated pleiotropy effect, namely "sigmaeta", which is "The variance estimate for the uncorrelated pleiotropy effect".
Do I need to evaluate the pleiotropy effect based on these outputs? or MRAID already accounts for both pleiotropy effects, so the results "causal_effect" and "causal_pvalue" are already the results after accounted for pleiotropy.
Thanks a lot for your help.

Best,
Yue

**Comment by arkyl** [comment]
Thanks a lot for the explanation. Please close the thread.
